from app import create_app, db
from app.models import Book

app = create_app()

descriptions = {
    "To Kill a Mockingbird": "A powerful story of racial injustice and moral growth in the American South, seen through the eyes of young Scout Finch.",
    "1984": "A chilling dystopian novel about a totalitarian society where Big Brother watches your every move and independent thought is a crime.",
    "The Great Gatsby": "A tragic tale of wealth, love, and the American Dream set in the glittering 1920s New York.",
    "Harry Potter and the Philosopher's Stone": "A young boy discovers he is a wizard and begins his magical education at Hogwarts School of Witchcraft and Wizardry.",
    "The Hobbit": "Bilbo Baggins, a comfort-loving hobbit, embarks on an unexpected adventure with a group of dwarves to reclaim their mountain home.",
    "Pride and Prejudice": "A witty and romantic novel about Elizabeth Bennet and Mr. Darcy as they navigate love, class, and misunderstanding.",
    "The Da Vinci Code": "A Harvard symbologist races to solve a murder inside the Louvre that leads to a centuries-old secret society conspiracy.",
    "Brave New World": "A dystopian vision of a future society controlled by technology, conditioning, and the elimination of human emotion.",
    "The Catcher in the Rye": "Teenager Holden Caulfield wanders New York City after being expelled from school, reflecting on authenticity and alienation.",
    "The Alchemist": "A shepherd boy travels from Spain to Egypt in pursuit of his personal legend, learning profound life lessons along the way.",
    "Lord of the Flies": "A group of British schoolboys stranded on a desert island descend into savagery as they struggle to survive without adult supervision.",
    "Animal Farm": "A satirical fable in which farm animals overthrow their human farmer, only to find themselves under an even more oppressive regime.",
    "The Hunger Games": "In a dystopian future, teenagers are forced to compete in a televised death match as punishment for past rebellion.",
    "Fahrenheit 451": "In a future where books are banned and burned, a fireman begins to question the society he serves.",
    "The Lord of the Rings": "An epic fantasy quest to destroy the One Ring and defeat the dark lord Sauron, with the fate of Middle-earth at stake.",
    "Crime and Punishment": "A Russian student murders a pawnbroker and struggles with guilt and moral philosophy in pre-revolutionary St. Petersburg.",
    "The Shining": "A family isolated in a haunted Colorado hotel during winter faces supernatural terror and a father's descent into madness.",
    "Gone with the Wind": "A sweeping epic of love and survival set against the backdrop of the American Civil War and Reconstruction era.",
    "The Odyssey": "Homer's ancient epic follows Odysseus on his treacherous ten-year journey home after the fall of Troy.",
    "Moby Dick": "Captain Ahab's obsessive quest to hunt the white whale that cost him his leg drives his crew toward destruction.",
    "The Picture of Dorian Gray": "A beautiful young man sells his soul to remain forever young while his portrait ages and reflects his moral corruption.",
    "Jane Eyre": "An orphaned governess falls in love with her mysterious employer Mr. Rochester, whose dark secret threatens their happiness.",
    "Wuthering Heights": "A passionate and destructive love story between Heathcliff and Catherine set on the wild Yorkshire moors.",
    "The Count of Monte Cristo": "A falsely imprisoned man escapes and reinvents himself as a wealthy count to exact elaborate revenge on his enemies.",
    "Les Misérables": "An epic tale of justice, love, and redemption following ex-convict Jean Valjean in post-revolutionary France.",
    "The Girl with the Dragon Tattoo": "A disgraced journalist and a brilliant hacker investigate a decades-old disappearance within a wealthy Swedish family.",
    "Gone Girl": "A thriller told from two perspectives as a wife goes missing and her husband becomes the prime suspect.",
    "The Maze Runner": "A teenage boy wakes in a mysterious maze with no memory and must work with others to find a way out.",
    "Divergent": "In a future society divided into factions, a girl discovers she doesn't fit any category and uncovers a dangerous conspiracy.",
    "The Fault in Our Stars": "Two teenagers with cancer fall in love and embark on a journey to meet their favorite author in Amsterdam.",
    "Sapiens": "A groundbreaking narrative of humanity's creation and evolution, exploring how Homo sapiens came to dominate the Earth.",
    "A Brief History of Time": "Stephen Hawking explores the nature of time, black holes, and the origin of the universe in accessible terms.",
    "Thinking, Fast and Slow": "Nobel laureate Daniel Kahneman explains the two systems that drive the way we think and make decisions.",
    "The Power of Now": "A spiritual guide to enlightenment that teaches readers to live fully in the present moment.",
    "Rich Dad Poor Dad": "Personal finance lessons contrasting the money mindset of the author's two father figures.",
    "The 7 Habits of Highly Effective People": "Seven principles for personal and professional effectiveness that have transformed millions of lives.",
    "How to Win Friends and Influence People": "Timeless advice on building relationships, communicating effectively, and influencing others positively.",
    "The Art of War": "Ancient Chinese military treatise offering timeless wisdom on strategy, leadership, and conflict resolution.",
    "Steve Jobs": "The authorized biography of Apple's visionary co-founder, revealing his genius, passion, and complex personality.",
    "The Diary of a Young Girl": "Anne Frank's moving account of hiding from the Nazis in a secret Amsterdam annex during World War II.",
    "Long Walk to Freedom": "Nelson Mandela's autobiography tracing his journey from rural South Africa to 27 years in prison to the presidency.",
    "Clean Code": "A handbook of agile software craftsmanship teaching programmers to write clean, maintainable, and efficient code.",
    "The Pragmatic Programmer": "Essential advice for software developers on becoming more effective, adaptable, and valuable in their craft.",
    "Introduction to Algorithms": "The definitive textbook on algorithms, covering a broad range of topics with rigorous mathematical analysis.",
    "The Selfish Gene": "Richard Dawkins presents a gene-centered view of evolution, introducing the concept of the meme.",
    "Guns, Germs, and Steel": "An explanation of why some civilizations came to dominate others based on geography and environment.",
    "The Hitchhiker's Guide to the Galaxy": "A comedic science fiction adventure following Arthur Dent after Earth is demolished for a hyperspace bypass.",
    "Dune": "A science fiction epic set on a desert planet rich with a precious spice, exploring politics, religion, and ecology.",
    "The Road": "A father and son journey through a post-apocalyptic America, struggling to survive and maintain their humanity.",
    "Of Mice and Men": "Two displaced migrant workers dream of owning their own land in Depression-era California.",
    "The Old Man and the Sea": "An aging Cuban fisherman struggles with a giant marlin far out in the Gulf Stream in Hemingway's Pulitzer Prize winner.",
    "Dracula": "Bram Stoker's classic gothic horror novel about Count Dracula's attempt to move from Transylvania to England.",
    "Frankenstein": "Mary Shelley's pioneering science fiction novel about a scientist who creates life and the consequences that follow.",
    "Atomic Habits": "A practical guide to building good habits and breaking bad ones through small, incremental changes.",
    "Deep Work": "Cal Newport argues that the ability to focus without distraction is the superpower of the 21st century.",
    "Mindset": "Carol Dweck's research reveals how a growth mindset can help people achieve their full potential.",
    "The Subtle Art of Not Giving a F*ck": "A counterintuitive approach to living a good life by focusing only on what truly matters.",
    "Ikigai": "The Japanese secret to a long and happy life, finding the intersection of passion, mission, and purpose.",
    "Man's Search for Meaning": "Viktor Frankl's profound account of life in Nazi concentration camps and his psychotherapy method.",
    "The Body Keeps the Score": "How trauma reshapes the body and brain, and innovative treatments for recovery.",
    "Educated": "Tara Westover's memoir about growing up in a survivalist family in rural Idaho and educating herself out of it.",
    "Becoming": "Michelle Obama's inspiring memoir of her journey from Chicago's South Side to the White House.",
    "Meditations": "Personal writings of Roman Emperor Marcus Aurelius reflecting on Stoic philosophy and self-improvement.",
    "The Stranger": "Albert Camus' existentialist novel about a detached man who commits a senseless murder in Algeria.",
    "Siddhartha": "Hermann Hesse's novel of self-discovery following a young man's spiritual journey in ancient India.",
    "The Martian": "An astronaut is stranded on Mars and must use his ingenuity to survive until rescue can arrive.",
    "Project Hail Mary": "A lone astronaut wakes up with no memory millions of miles from Earth on a mission to save humanity.",
    "A Game of Thrones": "The first book in an epic fantasy series of political intrigue, war, and power in the Seven Kingdoms.",
    "The Silent Patient": "A famous painter shoots her husband and then stops speaking, leaving her therapist to unravel the mystery.",
    "It Ends with Us": "A powerful story about love, choices, and breaking the cycle of abuse.",
    "The Kite Runner": "A story of friendship, betrayal, and redemption set against Afghanistan's turbulent history.",
    "A Thousand Splendid Suns": "Two Afghan women bound by friendship and fate survive decades of war and oppression.",
    "Hamlet": "Shakespeare's tragic masterpiece about a Danish prince who seeks revenge for his father's murder.",
    "Romeo and Juliet": "Shakespeare's timeless tale of two young lovers from feuding families in Verona.",
}

with app.app_context():
    updated = 0
    for book in Book.query.all():
        if book.title in descriptions:
            book.description = descriptions[book.title]
            updated += 1
    db.session.commit()
    print(f'Updated {updated} books with descriptions')