from app import create_app, db
from app.models import Book

app = create_app()

descriptions = {
    "The Kite Runner": "A story of friendship, betrayal, and redemption set against Afghanistan's turbulent history from the 1970s to post-Taliban era.",
    "A Thousand Splendid Suns": "Two Afghan women bound by friendship and fate survive decades of war, loss, and oppression in Kabul.",
    "Beloved": "A former slave is haunted by the ghost of her dead daughter in post-Civil War Ohio in Morrison's Pulitzer Prize winner.",
    "The Color Purple": "An African American woman's journey to self-discovery and empowerment in the American South during the 1930s.",
    "Anna Karenina": "A Russian aristocrat risks everything for a passionate affair, exploring themes of love, jealousy, and social hypocrisy.",
    "War and Peace": "Tolstoy's sweeping masterpiece follows five aristocratic families through Napoleon's 1812 invasion of Russia.",
    "The Brothers Karamazov": "Dostoevsky's final novel explores faith, doubt, and morality through three brothers and their father's murder.",
    "One Hundred Years of Solitude": "Seven generations of the Buendía family in the fictional town of Macondo in García Márquez's magical realist masterpiece.",
    "Love in the Time of Cholera": "An epic love story spanning over fifty years in a Caribbean port city, exploring obsession, aging, and devotion.",
    "The Sun Also Rises": "American expatriates in 1920s Paris and Pamplona navigate love, disillusionment, and the aftermath of World War I.",
    "A Farewell to Arms": "An American ambulance driver falls in love with a British nurse during World War I in Hemingway's semi-autobiographical novel.",
    "The Grapes of Wrath": "The Joad family's desperate migration from Oklahoma to California during the Great Depression.",
    "East of Eden": "Steinbeck's epic retelling of the Cain and Abel story through two families in California's Salinas Valley.",
    "Invisible Man": "An unnamed Black man's journey through a racist American society that refuses to see him as a human being.",
    "Their Eyes Were Watching God": "Janie Crawford's search for identity and love in early 20th century Black Southern communities.",
    "Never Let Me Go": "Students at an English boarding school gradually discover the dark truth about their existence and purpose.",
    "The Remains of the Day": "An English butler reflects on his life of service and the personal sacrifices he made for professional dignity.",
    "Atonement": "A misidentification by a young girl has devastating consequences for her sister and her lover in pre-war England.",
    "Normal People": "The complex relationship between two Irish teenagers as they navigate love, class, and identity through college.",
    "Ender's Game": "A child military genius is trained in a space battle school to lead humanity's defense against an alien invasion.",
    "Foundation": "A mathematician develops psychohistory to predict and shorten the coming dark age of a collapsing galactic empire.",
    "I, Robot": "Nine interconnected stories exploring the relationship between humans and robots governed by the Three Laws of Robotics.",
    "Neuromancer": "A washed-up hacker is hired for one last job that takes him into the virtual reality cyberspace of a global computer network.",
    "The Left Hand of Darkness": "A human envoy visits a planet where the inhabitants have no fixed gender in Le Guin's groundbreaking science fiction.",
    "Slaughterhouse-Five": "Billy Pilgrim becomes unstuck in time, experiencing his WWII capture and the bombing of Dresden repeatedly.",
    "The Martian": "Stranded alone on Mars after a mission abort, astronaut Mark Watney must use science and humor to survive.",
    "Project Hail Mary": "A lone astronaut wakes with amnesia millions of miles from Earth and must remember his mission to save humanity.",
    "Recursion": "A neuroscientist's memory-altering technology threatens to unravel reality itself in this mind-bending thriller.",
    "Dark Matter": "A physicist is kidnapped and wakes in a parallel universe where he must find his way back to his own life.",
    "A Game of Thrones": "Noble families battle for control of the Iron Throne while an ancient evil stirs beyond the kingdom's northern border.",
    "The Name of the Wind": "The legendary wizard Kvothe tells the true story of his life — from gifted child to notorious outcast.",
    "The Way of Kings": "In a world ravaged by storms, a soldier, a scholar, and a thief are drawn into an ancient war with cosmic stakes.",
    "Mistborn: The Final Empire": "A group of rebels plan to overthrow a seemingly immortal dark lord using a magic system based on ingested metals.",
    "American Gods": "An ex-convict is drawn into a conflict between ancient gods brought to America by immigrants and new gods of media and technology.",
    "Good Omens": "An angel and a demon reluctantly team up to prevent the apocalypse — because they've grown rather fond of Earth.",
    "The Chronicles of Narnia": "Seven children discover a magical world through a wardrobe where they help the lion Aslan battle the White Witch.",
    "Eragon": "A farm boy discovers a dragon egg and is thrust into an epic battle between the Riders and an evil king.",
    "The Sword of Kaigen": "A woman warrior rediscovers her fighting spirit when outside forces threaten her isolated Japanese-inspired village.",
    "Six of Crows": "A criminal prodigy leads a crew of dangerous outcasts on an impossible heist in a richly built fantasy world.",
    "And Then There Were None": "Ten strangers are lured to a remote island and begin to die one by one, matching a sinister nursery rhyme.",
    "Murder on the Orient Express": "Detective Hercule Poirot investigates a murder committed on a snowbound luxury train.",
    "The Hound of the Baskervilles": "Sherlock Holmes investigates the legend of a supernatural hound terrorizing a noble family on the moors.",
    "In the Woods": "A Dublin detective investigating a child's murder finds it linked to a childhood trauma he cannot remember.",
    "The Big Sleep": "Private detective Philip Marlowe is hired by a dying general and pulled into a web of blackmail and murder in Los Angeles.",
    "The Silent Patient": "A famous painter shoots her husband five times and then stops speaking — forever. Or so everyone thinks.",
    "Big Little Lies": "Three women with seemingly perfect lives become entangled in a murder investigation in an Australian beach town.",
    "The Girl on the Train": "An alcoholic woman becomes obsessed with a couple she observes daily from her commuter train — until one goes missing.",
    "The Bourne Identity": "An amnesiac found floating in the Mediterranean must piece together his identity while being hunted by assassins.",
    "No Country for Old Men": "A hunter stumbles upon a drug deal gone wrong and takes the money, setting off a violent chain of events.",
    "The Pelican Brief": "A law student's theory about two Supreme Court justices' assassinations puts her life in grave danger.",
    "Along Came a Spider": "Detective Alex Cross investigates the kidnapping of a senator's daughter by a brilliant and sadistic killer.",
    "I Am Pilgrim": "A retired intelligence agent is pulled back in to stop a terrorist plot to unleash a plague on America.",
    "It": "Seven friends face a terrifying shape-shifting monster in their childhood and must confront it again as adults.",
    "Pet Sematary": "A family discovers an ancient burial ground near their new home with the power to bring the dead back to life.",
    "Misery": "A famous novelist is rescued from a car crash by his self-proclaimed biggest fan — who then holds him captive.",
    "Interview with the Vampire": "A vampire tells his life story from 18th century New Orleans to a reporter in present-day San Francisco.",
    "House of Leaves": "A family discovers their house is larger on the inside than the outside in this experimental horror novel.",
    "The Haunting of Hill House": "Four people spend a summer in a notoriously haunted mansion, and one of them may not make it out alive.",
    "The Giver": "In a seemingly perfect community, a boy is chosen to be the keeper of all painful memories of the past.",
    "Holes": "A boy is sent to a detention camp where the warden forces kids to dig holes in the desert, hiding a dark secret.",
    "The Perks of Being a Wallflower": "A shy teenager navigates high school friendship, love, and trauma through letters to an anonymous friend.",
    "Speak": "A high school freshman stops speaking after a traumatic event and must find the courage to break her silence.",
    "The Outsiders": "Two rival gangs — the Greasers and the Socs — clash in 1960s Oklahoma in this coming-of-age classic.",
    "Tuesdays with Morrie": "A sportswriter visits his dying college professor every Tuesday, learning profound lessons about life and death.",
    "The House on Mango Street": "A series of vignettes following a young Latina girl growing up in Chicago and dreaming of a better life.",
    "Sense and Sensibility": "Two sisters seek love and financial security in a society that judges women by their marriages.",
    "Emma": "A well-meaning but misguided young woman meddles in the romantic lives of her friends and neighbors.",
    "Outlander": "A WWII nurse is transported back to 18th century Scotland and torn between two men from different centuries.",
    "Me Before You": "A young woman becomes caregiver to a paralyzed man and forms an unexpected bond that changes her life forever.",
    "The Notebook": "A devoted man reads to an elderly woman from a notebook, revealing their youthful summer romance.",
    "It Ends with Us": "A powerful story of a woman who must make an impossible choice between love and survival.",
    "The Time Traveler's Wife": "A man with a genetic disorder involuntarily time travels, and his wife must cope with his unpredictable disappearances.",
    "The Rise and Fall of the Third Reich": "A definitive history of Nazi Germany from its origins to its catastrophic defeat in World War II.",
    "Homo Deus": "Yuval Noah Harari explores humanity's future as technology and data threaten to make humans obsolete.",
    "The Silk Roads": "A revisionist history revealing how the routes connecting East and West shaped the modern world.",
    "SPQR: A History of Ancient Rome": "Mary Beard's accessible and provocative history of ancient Rome and its relevance to the modern world.",
    "The Crusades": "A comprehensive history of the medieval holy wars between Christian and Muslim forces in the Holy Land.",
    "1776": "David McCullough's gripping account of the pivotal year in which America fought for and won its independence.",
    "The Diary of a Young Girl (Definitive Edition)": "The complete and restored diary of Anne Frank during her years in hiding from the Nazis.",
    "The Origin of Species": "Darwin's groundbreaking 1859 work introducing the theory of evolution by natural selection.",
    "Cosmos": "Carl Sagan's lyrical exploration of the universe, from the Big Bang to the search for extraterrestrial intelligence.",
    "The Double Helix": "James Watson's personal account of the discovery of the structure of DNA and the race to unravel life's secret.",
    "Surely You're Joking, Mr. Feynman!": "Physicist Richard Feynman's hilarious and brilliant memoir of a life lived with insatiable curiosity.",
    "The Gene: An Intimate History": "A sweeping history of the gene and how our growing ability to manipulate DNA will change humanity.",
    "Being Mortal": "Atul Gawande examines how medicine can improve end-of-life care and what it means to die well.",
    "The Emperor of All Maladies": "A biography of cancer tracing its history from ancient times to modern treatments.",
    "The Body Keeps the Score": "Bessel van der Kolk reveals how trauma reshapes the body and brain, and explores innovative treatments.",
    "Influence": "Robert Cialdini identifies six key principles of persuasion that govern how we are influenced by others.",
    "Quiet: The Power of Introverts": "Susan Cain argues that introverts are undervalued in a world that celebrates extroversion.",
    "Flow": "Psychologist Mihaly Csikszentmihalyi explores the state of optimal experience and how to achieve it.",
    "The Interpretation of Dreams": "Freud's landmark 1899 work introducing the idea that dreams are the royal road to the unconscious mind.",
    "Deep Work": "Cal Newport argues that focused, distraction-free work is the key skill of the 21st century knowledge economy.",
    "Mindset": "Carol Dweck's research shows that a growth mindset — believing abilities can be developed — leads to greater achievement.",
    "The Subtle Art of Not Giving a F*ck": "Mark Manson's counterintuitive approach to living a good life by choosing what truly matters.",
    "Ikigai": "The Japanese concept of finding life's purpose through the intersection of passion, mission, vocation, and profession.",
    "Grit": "Angela Duckworth's research shows that passion and perseverance — not talent — predict outstanding achievement.",
    "Zero to One": "Peter Thiel's contrarian thinking on building startups that create genuinely new things rather than copying existing ones.",
    "The Lean Startup": "Eric Ries introduces a methodology for developing businesses and products that aims to shorten product development cycles.",
    "Good to Great": "Jim Collins' research reveals why some companies make the leap to greatness and others don't.",
    "The Innovator's Dilemma": "Why successful companies fail when confronted with disruptive innovation, and what to do about it.",
    "Thinking in Systems": "Donella Meadows introduces systems thinking as a way to understand and solve complex real-world problems.",
    "The Hard Thing About Hard Things": "Ben Horowitz shares hard-won insights on building and running a startup from someone who has done it.",
    "Shoe Dog": "Phil Knight's memoir about the creation of Nike from a $50 loan to a multi-billion dollar empire.",
    "Educated": "Tara Westover's memoir of growing up in a survivalist family in rural Idaho and educating herself into Cambridge.",
    "Becoming": "Michelle Obama's intimate and powerful memoir of her journey from Chicago's South Side to the White House.",
    "The Story of My Experiments with Truth": "Mahatma Gandhi's autobiography tracing his spiritual and political journey toward nonviolent resistance.",
    "Leonardo da Vinci": "Walter Isaacson's biography of history's greatest creative genius, based on Leonardo's notebooks.",
    "Einstein: His Life and Universe": "A comprehensive biography of Albert Einstein exploring his scientific breakthroughs and complex personal life.",
    "Alexander Hamilton": "Ron Chernow's definitive biography of the Founding Father who shaped modern America.",
    "The Autobiography of Malcolm X": "Malcolm X's powerful autobiography tracing his transformation from street criminal to Black nationalist leader.",
    "Meditations": "Personal writings of Roman Emperor Marcus Aurelius on Stoic philosophy, duty, and self-improvement.",
    "Thus Spoke Zarathustra": "Nietzsche's philosophical novel presenting his ideas on the Übermensch, will to power, and eternal recurrence.",
    "Beyond Good and Evil": "Nietzsche challenges traditional moral values and calls for a revaluation of all values.",
    "The Republic": "Plato's foundational work on justice, the ideal state, and the nature of the philosopher-king.",
    "Nicomachean Ethics": "Aristotle's treatise on virtue, happiness, and the good life that has shaped Western moral philosophy.",
    "Being and Nothingness": "Sartre's major philosophical work laying out the foundations of existentialism and radical human freedom.",
    "The Stranger": "Meursault kills an Arab on an Algerian beach and faces trial not for the murder but for his emotional indifference.",
    "Siddhartha": "A young Brahmin leaves his privileged life to seek enlightenment, eventually finding it through lived experience.",
    "The Mythical Man-Month": "Fred Brooks' classic essays on software engineering project management and why adding manpower slows projects.",
    "Design Patterns": "The Gang of Four's landmark catalog of reusable object-oriented software design solutions.",
    "You Don't Know JS": "A deep dive into JavaScript's core mechanisms that most developers misunderstand or overlook.",
    "The Linux Command Line": "A comprehensive introduction to using the Linux command line for beginners and experienced users alike.",
    "Automate the Boring Stuff with Python": "Practical Python programming for total beginners, teaching automation of everyday computer tasks.",
    "The Phoenix Project": "A novel about IT, DevOps, and helping your business win, told through a company facing catastrophic project failure.",
    "Cracking the Coding Interview": "189 programming interview questions with solutions and strategies for landing a job at top tech companies.",
    "The Man Who Knew Infinity": "The biography of Srinivasa Ramanujan, the self-taught mathematical genius from India.",
    "Fermat's Last Theorem": "The story of the 350-year quest to prove Fermat's deceptively simple mathematical conjecture.",
    "How to Solve It": "George Polya's classic guide to mathematical problem-solving strategies applicable to any discipline.",
    "The Art of Problem Solving Vol. 1": "The definitive guide for students preparing for mathematics competitions at all levels.",
    "Into the Wild": "The true story of Chris McCandless who abandoned his possessions to live in the Alaskan wilderness.",
    "Into Thin Air": "Jon Krakauer's harrowing first-hand account of the 1996 Mount Everest disaster that killed eight climbers.",
    "The Call of the Wild": "A domesticated dog is thrust into the brutal life of the Yukon gold rush and rediscovers his wild nature.",
    "Treasure Island": "Young Jim Hawkins embarks on a dangerous sea voyage to find buried pirate treasure.",
    "Around the World in 80 Days": "English gentleman Phileas Fogg bets he can circumnavigate the globe in 80 days.",
    "Twenty Thousand Leagues Under the Sea": "Captain Nemo takes prisoners on an extraordinary voyage aboard his submarine the Nautilus.",
    "Death of a Salesman": "Arthur Miller's masterpiece about the tragic collapse of Willy Loman and the American Dream.",
    "A Raisin in the Sun": "A Black family in 1950s Chicago debates how to spend a life insurance check in Hansberry's groundbreaking play.",
    "The Glass Menagerie": "Tennessee Williams' memory play about a domineering mother, her restless son, and her fragile daughter.",
    "Hamlet": "Shakespeare's tragic masterpiece about a Danish prince torn between action and inaction after his father's murder.",
    "Macbeth": "Shakespeare's darkest tragedy follows a Scottish general whose ambition, spurred by witches, leads to his downfall.",
    "Romeo and Juliet": "The timeless tragedy of two young lovers from feuding families whose love ends in heartbreak.",
    "Othello": "Shakespeare's tragedy of jealousy and manipulation as Iago destroys the noble Moor Othello.",
    "The Bible (NIV)": "The New International Version of the sacred scriptures of Christianity, containing the Old and New Testaments.",
    "The Quran (English Translation)": "M.A.S. Abdel Haleem's acclaimed English translation of Islam's holy scripture.",
    "Siddhartha": "Hermann Hesse's timeless tale of one man's spiritual journey toward enlightenment in ancient India.",
    "The Bhagavad Gita": "The ancient Hindu scripture presenting a conversation between Prince Arjuna and the god Krishna on duty and righteousness.",
    "The Tao Te Ching": "Laozi's ancient Chinese text of 81 verses on the nature of the Tao and how to live in harmony with it.",
    "Man's Search for Meaning": "Viktor Frankl's profound account of survival in Nazi death camps and his discovery of meaning as life's driving force.",
    "Homo Deus": "Harari's provocative exploration of humanity's future as biotechnology and artificial intelligence redefine what it means to be human.",
    "Rich Dad Poor Dad": "Robert Kiyosaki contrasts the financial philosophies of his educated but poor father and his friend's wealthy father.",
    "The 7 Habits of Highly Effective People": "Stephen Covey's timeless principles for personal and interpersonal effectiveness.",
    "How to Win Friends and Influence People": "Dale Carnegie's classic guide to building meaningful relationships and influencing others positively.",
    "The Art of War": "Sun Tzu's ancient treatise on military strategy has become essential reading for business and leadership.",
    "Steve Jobs": "Walter Isaacson's authorized biography reveals the genius, passion, and demons of Apple's visionary founder.",
}

with app.app_context():
    updated = 0
    for book in Book.query.all():
        if book.title in descriptions and not book.description:
            book.description = descriptions[book.title]
            updated += 1
    db.session.commit()
    print(f'Updated {updated} additional books with descriptions')