from app import create_app, db
from app.models import Book

app = create_app()

books = [
    # --- Fiction ---
    {"title": "The Kite Runner", "author": "Khaled Hosseini", "isbn": "9781594631931", "category": "Fiction", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg"},
    {"title": "A Thousand Splendid Suns", "author": "Khaled Hosseini", "isbn": "9781594489501", "category": "Fiction", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9781594489501-L.jpg"},
    {"title": "Beloved", "author": "Toni Morrison", "isbn": "9781400033416", "category": "Fiction", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9781400033416-L.jpg"},
    {"title": "The Color Purple", "author": "Alice Walker", "isbn": "9780156028356", "category": "Fiction", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780156028356-L.jpg"},
    {"title": "Middlemarch", "author": "George Eliot", "isbn": "9780141439549", "category": "Fiction", "copies": 3, "rating": 4.1, "cover": "https://covers.openlibrary.org/b/isbn/9780141439549-L.jpg"},
    {"title": "Anna Karenina", "author": "Leo Tolstoy", "isbn": "9780143035008", "category": "Fiction", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780143035008-L.jpg"},
    {"title": "War and Peace", "author": "Leo Tolstoy", "isbn": "9780199232765", "category": "Fiction", "copies": 3, "rating": 4.1, "cover": "https://covers.openlibrary.org/b/isbn/9780199232765-L.jpg"},
    {"title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky", "isbn": "9780374528379", "category": "Fiction", "copies": 3, "rating": 4.1, "cover": "https://covers.openlibrary.org/b/isbn/9780374528379-L.jpg"},
    {"title": "One Hundred Years of Solitude", "author": "Gabriel Garcia Marquez", "isbn": "9780060883287", "category": "Fiction", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg"},
    {"title": "Love in the Time of Cholera", "author": "Gabriel Garcia Marquez", "isbn": "9780307389732", "category": "Fiction", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780307389732-L.jpg"},
    {"title": "The Sun Also Rises", "author": "Ernest Hemingway", "isbn": "9780743297332", "category": "Fiction", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780743297332-L.jpg"},
    {"title": "A Farewell to Arms", "author": "Ernest Hemingway", "isbn": "9780684801469", "category": "Fiction", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780684801469-L.jpg"},
    {"title": "The Grapes of Wrath", "author": "John Steinbeck", "isbn": "9780143039433", "category": "Fiction", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780143039433-L.jpg"},
    {"title": "East of Eden", "author": "John Steinbeck", "isbn": "9780142004234", "category": "Fiction", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780142004234-L.jpg"},
    {"title": "Invisible Man", "author": "Ralph Ellison", "isbn": "9780679732761", "category": "Fiction", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780679732761-L.jpg"},
    {"title": "Their Eyes Were Watching God", "author": "Zora Neale Hurston", "isbn": "9780061350344", "category": "Fiction", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780061350344-L.jpg"},
    {"title": "Never Let Me Go", "author": "Kazuo Ishiguro", "isbn": "9781400078776", "category": "Fiction", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9781400078776-L.jpg"},
    {"title": "The Remains of the Day", "author": "Kazuo Ishiguro", "isbn": "9780679731726", "category": "Fiction", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780679731726-L.jpg"},
    {"title": "Atonement", "author": "Ian McEwan", "isbn": "9780385721790", "category": "Fiction", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780385721790-L.jpg"},
    {"title": "Normal People", "author": "Sally Rooney", "isbn": "9781984822185", "category": "Fiction", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9781984822185-L.jpg"},
 
    # --- Science Fiction ---
    {"title": "Ender's Game", "author": "Orson Scott Card", "isbn": "9780812550702", "category": "Science Fiction", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9780812550702-L.jpg"},
    {"title": "Foundation", "author": "Isaac Asimov", "isbn": "9780553293357", "category": "Science Fiction", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg"},
    {"title": "I, Robot", "author": "Isaac Asimov", "isbn": "9780553294385", "category": "Science Fiction", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780553294385-L.jpg"},
    {"title": "Neuromancer", "author": "William Gibson", "isbn": "9780441569595", "category": "Science Fiction", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg"},
    {"title": "The Left Hand of Darkness", "author": "Ursula K. Le Guin", "isbn": "9780441478125", "category": "Science Fiction", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780441478125-L.jpg"},
    {"title": "Slaughterhouse-Five", "author": "Kurt Vonnegut", "isbn": "9780440180296", "category": "Science Fiction", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780440180296-L.jpg"},
    {"title": "The Martian", "author": "Andy Weir", "isbn": "9780804139021", "category": "Science Fiction", "copies": 8, "rating": 4.90, "cover": "https://covers.openlibrary.org/b/isbn/9780804139021-L.jpg"},
    {"title": "Project Hail Mary", "author": "Andy Weir", "isbn": "9780593135204", "category": "Science Fiction", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg"},
    {"title": "Recursion", "author": "Blake Crouch", "isbn": "9781524759780", "category": "Science Fiction", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9781524759780-L.jpg"},
    {"title": "Dark Matter", "author": "Blake Crouch", "isbn": "9781101904244", "category": "Science Fiction", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9781101904244-L.jpg"},
 
    # --- Fantasy ---
    {"title": "A Game of Thrones", "author": "George R.R. Martin", "isbn": "9780553381689", "category": "Fantasy", "copies": 8, "rating": 4.90, "cover": "https://covers.openlibrary.org/b/isbn/9780553381689-L.jpg"},
    {"title": "The Name of the Wind", "author": "Patrick Rothfuss", "isbn": "9780756404079", "category": "Fantasy", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9780756404079-L.jpg"},
    {"title": "The Way of Kings", "author": "Brandon Sanderson", "isbn": "9780765326355", "category": "Fantasy", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780765326355-L.jpg"},
    {"title": "Mistborn: The Final Empire", "author": "Brandon Sanderson", "isbn": "9780765311788", "category": "Fantasy", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780765311788-L.jpg"},
    {"title": "American Gods", "author": "Neil Gaiman", "isbn": "9780060558123", "category": "Fantasy", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780060558123-L.jpg"},
    {"title": "Good Omens", "author": "Terry Pratchett & Neil Gaiman", "isbn": "9780060853983", "category": "Fantasy", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780060853983-L.jpg"},
    {"title": "The Chronicles of Narnia", "author": "C.S. Lewis", "isbn": "9780066238500", "category": "Fantasy", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9780066238500-L.jpg"},
    {"title": "Eragon", "author": "Christopher Paolini", "isbn": "9780375826696", "category": "Fantasy", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780375826696-L.jpg"},
    {"title": "The Sword of Kaigen", "author": "M.L. Wang", "isbn": "9781733245401", "category": "Fantasy", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9781733245401-L.jpg"},
    {"title": "Six of Crows", "author": "Leigh Bardugo", "isbn": "9781627792127", "category": "Fantasy", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9781627792127-L.jpg"},
 
    # --- Mystery ---
    {"title": "And Then There Were None", "author": "Agatha Christie", "isbn": "9780062073488", "category": "Mystery", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg"},
    {"title": "Murder on the Orient Express", "author": "Agatha Christie", "isbn": "9780062073501", "category": "Mystery", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780062073501-L.jpg"},
    {"title": "The Hound of the Baskervilles", "author": "Arthur Conan Doyle", "isbn": "9780141034546", "category": "Mystery", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780141034546-L.jpg"},
    {"title": "In the Woods", "author": "Tana French", "isbn": "9780143113492", "category": "Mystery", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780143113492-L.jpg"},
    {"title": "The Big Sleep", "author": "Raymond Chandler", "isbn": "9780394758282", "category": "Mystery", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780394758282-L.jpg"},
    {"title": "The Silent Patient", "author": "Alex Michaelides", "isbn": "9781250301697", "category": "Mystery", "copies": 8, "rating": 4.90, "cover": "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg"},
    {"title": "Big Little Lies", "author": "Liane Moriarty", "isbn": "9780425274866", "category": "Mystery", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780425274866-L.jpg"},
 
    # --- Thriller ---
    {"title": "The Girl on the Train", "author": "Paula Hawkins", "isbn": "9781594634024", "category": "Thriller", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9781594634024-L.jpg"},
    {"title": "The Bourne Identity", "author": "Robert Ludlum", "isbn": "9780553260113", "category": "Thriller", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780553260113-L.jpg"},
    {"title": "No Country for Old Men", "author": "Cormac McCarthy", "isbn": "9780307387134", "category": "Thriller", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780307387134-L.jpg"},
    {"title": "The Pelican Brief", "author": "John Grisham", "isbn": "9780440214984", "category": "Thriller", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780440214984-L.jpg"},
    {"title": "Along Came a Spider", "author": "James Patterson", "isbn": "9780316693936", "category": "Thriller", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780316693936-L.jpg"},
    {"title": "I Am Pilgrim", "author": "Terry Hayes", "isbn": "9781476717494", "category": "Thriller", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9781476717494-L.jpg"},
 
    # --- Horror ---
    {"title": "It", "author": "Stephen King", "isbn": "9781501142970", "category": "Horror", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9781501142970-L.jpg"},
    {"title": "Pet Sematary", "author": "Stephen King", "isbn": "9781501156700", "category": "Horror", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9781501156700-L.jpg"},
    {"title": "Misery", "author": "Stephen King", "isbn": "9780451169525", "category": "Horror", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780451169525-L.jpg"},
    {"title": "Interview with the Vampire", "author": "Anne Rice", "isbn": "9780345409645", "category": "Horror", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780345409645-L.jpg"},
    {"title": "House of Leaves", "author": "Mark Z. Danielewski", "isbn": "9780375703768", "category": "Horror", "copies": 3, "rating": 4.1, "cover": "https://covers.openlibrary.org/b/isbn/9780375703768-L.jpg"},
    {"title": "The Haunting of Hill House", "author": "Shirley Jackson", "isbn": "9780143039983", "category": "Horror", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780143039983-L.jpg"},
 
    # --- Young Adult ---
    {"title": "The Giver", "author": "Lois Lowry", "isbn": "9780544336261", "category": "Young Adult", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9780544336261-L.jpg"},
    {"title": "Holes", "author": "Louis Sachar", "isbn": "9780440228257", "category": "Young Adult", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780440228257-L.jpg"},
    {"title": "The Perks of Being a Wallflower", "author": "Stephen Chbosky", "isbn": "9781451696196", "category": "Young Adult", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9781451696196-L.jpg"},
    {"title": "Speak", "author": "Laurie Halse Anderson", "isbn": "9780312674397", "category": "Young Adult", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780312674397-L.jpg"},
    {"title": "The Outsiders", "author": "S.E. Hinton", "isbn": "9780142407332", "category": "Young Adult", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780142407332-L.jpg"},
    {"title": "Tuesdays with Morrie", "author": "Mitch Albom", "isbn": "9780767905923", "category": "Young Adult", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9780767905923-L.jpg"},
    {"title": "The House on Mango Street", "author": "Sandra Cisneros", "isbn": "9780679734772", "category": "Young Adult", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780679734772-L.jpg"},
 
    # --- Romance ---
    {"title": "Sense and Sensibility", "author": "Jane Austen", "isbn": "9780141439662", "category": "Romance", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780141439662-L.jpg"},
    {"title": "Emma", "author": "Jane Austen", "isbn": "9780141439587", "category": "Romance", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780141439587-L.jpg"},
    {"title": "Outlander", "author": "Diana Gabaldon", "isbn": "9780440212560", "category": "Romance", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780440212560-L.jpg"},
    {"title": "Me Before You", "author": "Jojo Moyes", "isbn": "9780143124542", "category": "Romance", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780143124542-L.jpg"},
    {"title": "The Notebook", "author": "Nicholas Sparks", "isbn": "9780446605236", "category": "Romance", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780446605236-L.jpg"},
    {"title": "It Ends with Us", "author": "Colleen Hoover", "isbn": "9781501110368", "category": "Romance", "copies": 8, "rating": 4.90, "cover": "https://covers.openlibrary.org/b/isbn/9781501110368-L.jpg"},
    {"title": "The Time Traveler's Wife", "author": "Audrey Niffenegger", "isbn": "9780156029438", "category": "Romance", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780156029438-L.jpg"},
 
    # --- History ---
    {"title": "The Rise and Fall of the Third Reich", "author": "William L. Shirer", "isbn": "9781451651683", "category": "History", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9781451651683-L.jpg"},
    {"title": "Homo Deus", "author": "Yuval Noah Harari", "isbn": "9780062464316", "category": "History", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780062464316-L.jpg"},
    {"title": "The Silk Roads", "author": "Peter Frankopan", "isbn": "9781101912379", "category": "History", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9781101912379-L.jpg"},
    {"title": "SPQR: A History of Ancient Rome", "author": "Mary Beard", "isbn": "9781631492228", "category": "History", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9781631492228-L.jpg"},
    {"title": "The Crusades", "author": "Thomas Asbridge", "isbn": "9780060787288", "category": "History", "copies": 3, "rating": 4.1, "cover": "https://covers.openlibrary.org/b/isbn/9780060787288-L.jpg"},
    {"title": "1776", "author": "David McCullough", "isbn": "9780743226721", "category": "History", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780743226721-L.jpg"},
    {"title": "The Diary of a Young Girl (Definitive Edition)", "author": "Anne Frank", "isbn": "9780385473781", "category": "History", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780385473781-L.jpg"},
 
    # --- Science ---
    {"title": "The Origin of Species", "author": "Charles Darwin", "isbn": "9780140432053", "category": "Science", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780140432053-L.jpg"},
    {"title": "Cosmos", "author": "Carl Sagan", "isbn": "9780345539434", "category": "Science", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780345539434-L.jpg"},
    {"title": "The Double Helix", "author": "James D. Watson", "isbn": "9780743216302", "category": "Science", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780743216302-L.jpg"},
    {"title": "Surely You're Joking, Mr. Feynman!", "author": "Richard Feynman", "isbn": "9780393316049", "category": "Science", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780393316049-L.jpg"},
    {"title": "The Gene: An Intimate History", "author": "Siddhartha Mukherjee", "isbn": "9781476733524", "category": "Science", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9781476733524-L.jpg"},
    {"title": "Being Mortal", "author": "Atul Gawande", "isbn": "9780805095159", "category": "Science", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780805095159-L.jpg"},
    {"title": "The Emperor of All Maladies", "author": "Siddhartha Mukherjee", "isbn": "9781439170915", "category": "Science", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9781439170915-L.jpg"},
 
    # --- Psychology ---
    {"title": "Man's Search for Meaning", "author": "Viktor E. Frankl", "isbn": "9780807014271", "category": "Psychology", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9780807014271-L.jpg"},
    {"title": "The Body Keeps the Score", "author": "Bessel van der Kolk", "isbn": "9780143127741", "category": "Psychology", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780143127741-L.jpg"},
    {"title": "Influence", "author": "Robert Cialdini", "isbn": "9780062937650", "category": "Psychology", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780062937650-L.jpg"},
    {"title": "Quiet: The Power of Introverts", "author": "Susan Cain", "isbn": "9780307352156", "category": "Psychology", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780307352156-L.jpg"},
    {"title": "Flow", "author": "Mihaly Csikszentmihalyi", "isbn": "9780061339202", "category": "Psychology", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780061339202-L.jpg"},
    {"title": "The Interpretation of Dreams", "author": "Sigmund Freud", "isbn": "9780465019779", "category": "Psychology", "copies": 3, "rating": 4.1, "cover": "https://covers.openlibrary.org/b/isbn/9780465019779-L.jpg"},
 
    # --- Self-Help ---
    {"title": "Atomic Habits", "author": "James Clear", "isbn": "9780735211292", "category": "Self-Help", "copies": 10, "cover": "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg"},
    {"title": "Deep Work", "author": "Cal Newport", "isbn": "9781455586691", "category": "Self-Help", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg"},
    {"title": "Mindset", "author": "Carol S. Dweck", "isbn": "9780345472328", "category": "Self-Help", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9780345472328-L.jpg"},
    {"title": "The Subtle Art of Not Giving a F*ck", "author": "Mark Manson", "isbn": "9780062457714", "category": "Self-Help", "copies": 8, "rating": 4.90, "cover": "https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg"},
    {"title": "Ikigai", "author": "Hector Garcia & Francesc Miralles", "isbn": "9780143130727", "category": "Self-Help", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780143130727-L.jpg"},
    {"title": "Grit", "author": "Angela Duckworth", "isbn": "9781501111105", "category": "Self-Help", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9781501111105-L.jpg"},
 
    # --- Business ---
    {"title": "Zero to One", "author": "Peter Thiel", "isbn": "9780804139298", "category": "Business", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg"},
    {"title": "The Lean Startup", "author": "Eric Ries", "isbn": "9780307887894", "category": "Business", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg"},
    {"title": "Good to Great", "author": "Jim Collins", "isbn": "9780066620992", "category": "Business", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg"},
    {"title": "The Innovator's Dilemma", "author": "Clayton M. Christensen", "isbn": "9780062060242", "category": "Business", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780062060242-L.jpg"},
    {"title": "Thinking in Systems", "author": "Donella H. Meadows", "isbn": "9781603580557", "category": "Business", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9781603580557-L.jpg"},
    {"title": "The Hard Thing About Hard Things", "author": "Ben Horowitz", "isbn": "9780062273208", "category": "Business", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780062273208-L.jpg"},
    {"title": "Shoe Dog", "author": "Phil Knight", "isbn": "9781501135927", "category": "Business", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9781501135927-L.jpg"},
 
    # --- Biography / Autobiography ---
    {"title": "Educated", "author": "Tara Westover", "isbn": "9780399590504", "category": "Autobiography", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg"},
    {"title": "Becoming", "author": "Michelle Obama", "isbn": "9781524763138", "category": "Autobiography", "copies": 8, "rating": 4.90, "cover": "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg"},
    {"title": "The Story of My Experiments with Truth", "author": "Mahatma Gandhi", "isbn": "9780807059098", "category": "Autobiography", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780807059098-L.jpg"},
    {"title": "Leonardo da Vinci", "author": "Walter Isaacson", "isbn": "9781501139154", "category": "Biography", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9781501139154-L.jpg"},
    {"title": "Einstein: His Life and Universe", "author": "Walter Isaacson", "isbn": "9780743264747", "category": "Biography", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780743264747-L.jpg"},
    {"title": "Alexander Hamilton", "author": "Ron Chernow", "isbn": "9780143034759", "category": "Biography", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780143034759-L.jpg"},
    {"title": "The Autobiography of Malcolm X", "author": "Malcolm X & Alex Haley", "isbn": "9780345350688", "category": "Autobiography", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780345350688-L.jpg"},
 
    # --- Philosophy ---
    {"title": "Meditations", "author": "Marcus Aurelius", "isbn": "9780812968255", "category": "Philosophy", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780812968255-L.jpg"},
    {"title": "Thus Spoke Zarathustra", "author": "Friedrich Nietzsche", "isbn": "9780140441185", "category": "Philosophy", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780140441185-L.jpg"},
    {"title": "Beyond Good and Evil", "author": "Friedrich Nietzsche", "isbn": "9780679724659", "category": "Philosophy", "copies": 3, "rating": 4.1, "cover": "https://covers.openlibrary.org/b/isbn/9780679724659-L.jpg"},
    {"title": "The Republic", "author": "Plato", "isbn": "9780872201361", "category": "Philosophy", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780872201361-L.jpg"},
    {"title": "Nicomachean Ethics", "author": "Aristotle", "isbn": "9780872204645", "category": "Philosophy", "copies": 3, "rating": 4.1, "cover": "https://covers.openlibrary.org/b/isbn/9780872204645-L.jpg"},
    {"title": "Being and Nothingness", "author": "Jean-Paul Sartre", "isbn": "9780671867805", "category": "Philosophy", "copies": 3, "rating": 4.1, "cover": "https://covers.openlibrary.org/b/isbn/9780671867805-L.jpg"},
    {"title": "The Stranger", "author": "Albert Camus", "isbn": "9780679720201", "category": "Philosophy", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780679720201-L.jpg"},
 
    # --- Technology ---
    {"title": "The Mythical Man-Month", "author": "Frederick P. Brooks Jr.", "isbn": "9780201835953", "category": "Technology", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780201835953-L.jpg"},
    {"title": "Design Patterns", "author": "Gang of Four", "isbn": "9780201633610", "category": "Technology", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780201633610-L.jpg"},
    {"title": "You Don't Know JS", "author": "Kyle Simpson", "isbn": "9781491924464", "category": "Technology", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9781491924464-L.jpg"},
    {"title": "The Linux Command Line", "author": "William Shotts", "isbn": "9781593279523", "category": "Technology", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9781593279523-L.jpg"},
    {"title": "Automate the Boring Stuff with Python", "author": "Al Sweigart", "isbn": "9781593279929", "category": "Technology", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9781593279929-L.jpg"},
    {"title": "The Phoenix Project", "author": "Gene Kim", "isbn": "9781942788294", "category": "Technology", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9781942788294-L.jpg"},
    {"title": "Cracking the Coding Interview", "author": "Gayle Laakmann McDowell", "isbn": "9780984782857", "category": "Technology", "copies": 7, "rating": 4.70, "cover": "https://covers.openlibrary.org/b/isbn/9780984782857-L.jpg"},
 
    # --- Mathematics ---
    {"title": "The Man Who Knew Infinity", "author": "Robert Kanigel", "isbn": "9780671750961", "category": "Mathematics", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780671750961-L.jpg"},
    {"title": "Fermat's Last Theorem", "author": "Simon Singh", "isbn": "9780385493628", "category": "Mathematics", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780385493628-L.jpg"},
    {"title": "How to Solve It", "author": "George Polya", "isbn": "9780691119663", "category": "Mathematics", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780691119663-L.jpg"},
    {"title": "The Art of Problem Solving Vol. 1", "author": "Sandor Lehoczky", "isbn": "9780977304561", "category": "Mathematics", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780977304561-L.jpg"},
 
    # --- Adventure ---
    {"title": "Into the Wild", "author": "Jon Krakauer", "isbn": "9780385486804", "category": "Adventure", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780385486804-L.jpg"},
    {"title": "Into Thin Air", "author": "Jon Krakauer", "isbn": "9780385494786", "category": "Adventure", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780385494786-L.jpg"},
    {"title": "The Call of the Wild", "author": "Jack London", "isbn": "9780486264721", "category": "Adventure", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780486264721-L.jpg"},
    {"title": "Treasure Island", "author": "Robert Louis Stevenson", "isbn": "9780141321004", "category": "Adventure", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780141321004-L.jpg"},
    {"title": "Around the World in 80 Days", "author": "Jules Verne", "isbn": "9780140449068", "category": "Adventure", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780140449068-L.jpg"},
    {"title": "Twenty Thousand Leagues Under the Sea", "author": "Jules Verne", "isbn": "9780140443530", "category": "Adventure", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780140443530-L.jpg"},
 
    # --- Drama ---
    {"title": "Death of a Salesman", "author": "Arthur Miller", "isbn": "9780140481341", "category": "Drama", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780140481341-L.jpg"},
    {"title": "A Raisin in the Sun", "author": "Lorraine Hansberry", "isbn": "9780679755333", "category": "Drama", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780679755333-L.jpg"},
    {"title": "The Glass Menagerie", "author": "Tennessee Williams", "isbn": "9780811214049", "category": "Drama", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780811214049-L.jpg"},
    {"title": "Hamlet", "author": "William Shakespeare", "isbn": "9780521618748", "category": "Drama", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780521618748-L.jpg"},
    {"title": "Macbeth", "author": "William Shakespeare", "isbn": "9780521618779", "category": "Drama", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780521618779-L.jpg"},
    {"title": "Romeo and Juliet", "author": "William Shakespeare", "isbn": "9780521618663", "category": "Drama", "copies": 6, "rating": 4.40, "cover": "https://covers.openlibrary.org/b/isbn/9780521618663-L.jpg"},
    {"title": "Othello", "author": "William Shakespeare", "isbn": "9780521618816", "category": "Drama", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780521618816-L.jpg"},
 
    # --- Religion / Spirituality ---
    {"title": "The Bible (NIV)", "author": "Various", "isbn": "9780310448914", "category": "Religion", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780310448914-L.jpg"},
    {"title": "The Quran (English Translation)", "author": "M.A.S. Abdel Haleem", "isbn": "9780192805486", "category": "Religion", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780192805486-L.jpg"},
    {"title": "Siddhartha", "author": "Hermann Hesse", "isbn": "9780553208849", "category": "Religion", "copies": 5, "rating": 4.61, "cover": "https://covers.openlibrary.org/b/isbn/9780553208849-L.jpg"},
    {"title": "The Bhagavad Gita", "author": "Anonymous", "isbn": "9780140449181", "category": "Religion", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780140449181-L.jpg"},
    {"title": "The Tao Te Ching", "author": "Laozi", "isbn": "9780061142666", "category": "Religion", "copies": 4, "rating": 4.2, "cover": "https://covers.openlibrary.org/b/isbn/9780061142666-L.jpg"},
]

descriptions = {
    "The Kite Runner": "A story of friendship, betrayal, and redemption set against Afghanistan's turbulent history from the 1970s to post-Taliban era.",
    "A Thousand Splendid Suns": "Two Afghan women bound by friendship and fate survive decades of war, loss, and oppression in Kabul.",
    "Beloved": "A former slave is haunted by the ghost of her dead daughter in post-Civil War Ohio in Morrison's Pulitzer Prize winner.",
    "The Color Purple": "An African American woman's journey to self-discovery and empowerment in the American South during the 1930s.",
    "Middlemarch": "A rich tapestry of provincial life in 19th-century England, following the lives and loves of the residents of Middlemarch.",
    "Anna Karenina": "A Russian aristocrat risks everything for a passionate affair, exploring themes of love, jealousy, and social hypocrisy.",
    "War and Peace": "Tolstoy's sweeping masterpiece follows five aristocratic families through Napoleon's 1812 invasion of Russia.",
    "The Brothers Karamazov": "Dostoevsky's final novel explores faith, doubt, and morality through three brothers and their father's murder.",
    "One Hundred Years of Solitude": "Seven generations of the Buendia family in the fictional town of Macondo in Garcia Marquez's magical realist masterpiece.",
    "Love in the Time of Cholera": "An epic love story spanning over fifty years in a Caribbean port city, exploring obsession, aging, and devotion.",
    "The Sun Also Rises": "American expatriates in 1920s Paris and Pamplona navigate love, disillusionment, and the aftermath of World War I.",
    "A Farewell to Arms": "An American ambulance driver falls in love with a British nurse during World War I in Hemingway's semi-autobiographical novel.",
    "The Grapes of Wrath": "The Joad family's desperate migration from Oklahoma to California during the Great Depression.",
    "East of Eden": "Steinbeck's epic retelling of the Cain and Abel story through two families in California's Salinas Valley.",
    "Invisible Man": "An unnamed Black man's journey through a racist American society that refuses to see him as a human being.",
    "Their Eyes Were Watching God": "Janie Crawford's search for identity and love in early 20th century Black Southern communities.",
    "Never Let Me Go": "Students at an English boarding school gradually discover the dark truth about their existence and purpose.",
    "The Remains of the Day": "An English butler reflects on his life of service and the personal sacrifices he made for professional dignity.",
    "Atonement": "A misidentification by a young girl has devastating consequences for her sister and her lover in pre-war England.",
    "Normal People": "The complex relationship between two Irish teenagers as they navigate love, class, and identity through college.",
    "Ender's Game": "A child military genius is trained in a space battle school to lead humanity's defense against an alien invasion.",
    "Foundation": "A mathematician develops psychohistory to predict and shorten the coming dark age of a collapsing galactic empire.",
    "I, Robot": "Nine interconnected stories exploring the relationship between humans and robots governed by the Three Laws of Robotics.",
    "Neuromancer": "A washed-up hacker is hired for one last job that takes him into the virtual reality cyberspace of a global computer network.",
    "The Left Hand of Darkness": "A human envoy visits a planet where the inhabitants have no fixed gender in Le Guin's groundbreaking science fiction.",
    "Slaughterhouse-Five": "Billy Pilgrim becomes unstuck in time, experiencing his WWII capture and the bombing of Dresden repeatedly.",
    "The Martian": "Stranded alone on Mars after a mission abort, astronaut Mark Watney must use science and humor to survive.",
    "Project Hail Mary": "A lone astronaut wakes with amnesia millions of miles from Earth and must remember his mission to save humanity.",
    "Recursion": "A neuroscientist's memory-altering technology threatens to unravel reality itself in this mind-bending thriller.",
    "Dark Matter": "A physicist is kidnapped and wakes in a parallel universe where he must find his way back to his own life.",
    "A Game of Thrones": "Noble families battle for control of the Iron Throne while an ancient evil stirs beyond the kingdom's northern border.",
    "The Name of the Wind": "The legendary wizard Kvothe tells the true story of his life from gifted child to notorious outcast.",
    "The Way of Kings": "In a world ravaged by storms, a soldier, a scholar, and a thief are drawn into an ancient war with cosmic stakes.",
    "Mistborn: The Final Empire": "A group of rebels plan to overthrow a seemingly immortal dark lord using a magic system based on ingested metals.",
    "American Gods": "An ex-convict is drawn into a conflict between ancient gods brought to America by immigrants and new gods of media and technology.",
    "Good Omens": "An angel and a demon reluctantly team up to prevent the apocalypse because they have grown rather fond of Earth.",
    "The Chronicles of Narnia": "Seven children discover a magical world through a wardrobe where they help the lion Aslan battle the White Witch.",
    "Eragon": "A farm boy discovers a dragon egg and is thrust into an epic battle between the Riders and an evil king.",
    "The Sword of Kaigen": "A woman warrior rediscovers her fighting spirit when outside forces threaten her isolated Japanese-inspired village.",
    "Six of Crows": "A criminal prodigy leads a crew of dangerous outcasts on an impossible heist in a richly built fantasy world.",
    "And Then There Were None": "Ten strangers are lured to a remote island and begin to die one by one, matching a sinister nursery rhyme.",
    "Murder on the Orient Express": "Detective Hercule Poirot investigates a murder committed on a snowbound luxury train.",
    "The Hound of the Baskervilles": "Sherlock Holmes investigates the legend of a supernatural hound terrorizing a noble family on the moors.",
    "In the Woods": "A Dublin detective investigating a child's murder finds it linked to a childhood trauma he cannot remember.",
    "The Big Sleep": "Private detective Philip Marlowe is hired by a dying general and pulled into a web of blackmail and murder in Los Angeles.",
    "The Silent Patient": "A famous painter shoots her husband five times and then stops speaking forever. Or so everyone thinks.",
    "Big Little Lies": "Three women with seemingly perfect lives become entangled in a murder investigation in an Australian beach town.",
    "The Girl on the Train": "An alcoholic woman becomes obsessed with a couple she observes daily from her commuter train until one goes missing.",
    "The Bourne Identity": "An amnesiac found floating in the Mediterranean must piece together his identity while being hunted by assassins.",
    "No Country for Old Men": "A hunter stumbles upon a drug deal gone wrong and takes the money, setting off a violent chain of events.",
    "The Pelican Brief": "A law student's theory about two Supreme Court justices' assassinations puts her life in grave danger.",
    "Along Came a Spider": "Detective Alex Cross investigates the kidnapping of a senator's daughter by a brilliant and sadistic killer.",
    "I Am Pilgrim": "A retired intelligence agent is pulled back in to stop a terrorist plot to unleash a plague on America.",
    "It": "Seven friends face a terrifying shape-shifting monster in their childhood and must confront it again as adults.",
    "Pet Sematary": "A family discovers an ancient burial ground near their new home with the power to bring the dead back to life.",
    "Misery": "A famous novelist is rescued from a car crash by his self-proclaimed biggest fan who then holds him captive.",
    "Interview with the Vampire": "A vampire tells his life story from 18th century New Orleans to a reporter in present-day San Francisco.",
    "House of Leaves": "A family discovers their house is larger on the inside than the outside in this experimental horror novel.",
    "The Haunting of Hill House": "Four people spend a summer in a notoriously haunted mansion, and one of them may not make it out alive.",
    "The Giver": "In a seemingly perfect community, a boy is chosen to be the keeper of all painful memories of the past.",
    "Holes": "A boy is sent to a detention camp where the warden forces kids to dig holes in the desert, hiding a dark secret.",
    "The Perks of Being a Wallflower": "A shy teenager navigates high school friendship, love, and trauma through letters to an anonymous friend.",
    "Speak": "A high school freshman stops speaking after a traumatic event and must find the courage to break her silence.",
    "The Outsiders": "Two rival gangs the Greasers and the Socs clash in 1960s Oklahoma in this coming-of-age classic.",
    "Tuesdays with Morrie": "A sportswriter visits his dying college professor every Tuesday, learning profound lessons about life and death.",
    "The House on Mango Street": "A series of vignettes following a young Latina girl growing up in Chicago and dreaming of a better life.",
    "Sense and Sensibility": "Two sisters seek love and financial security in a society that judges women by their marriages.",
    "Emma": "A well-meaning but misguided young woman meddles in the romantic lives of her friends and neighbors.",
    "Outlander": "A WWII nurse is transported back to 18th century Scotland and torn between two men from different centuries.",
    "Me Before You": "A young woman becomes caregiver to a paralyzed man and forms an unexpected bond that changes her life forever.",
    "The Notebook": "A devoted man reads to an elderly woman from a notebook, revealing their youthful summer romance.",
    "It Ends with Us": "A powerful story of a woman who must make an impossible choice between love and survival.",
    "The Time Traveler's Wife": "A man with a genetic disorder involuntarily time travels, and his wife must cope with his unpredictable disappearances.",
    "The Rise and Fall of the Third Reich": "A definitive history of Nazi Germany from its origins to its catastrophic defeat in World War II.",
    "Homo Deus": "Yuval Noah Harari explores humanity's future as technology and data threaten to make humans obsolete.",
    "The Silk Roads": "A revisionist history revealing how the routes connecting East and West shaped the modern world.",
    "SPQR: A History of Ancient Rome": "Mary Beard's accessible and provocative history of ancient Rome and its relevance to the modern world.",
    "The Crusades": "A comprehensive history of the medieval holy wars between Christian and Muslim forces in the Holy Land.",
    "1776": "David McCullough's gripping account of the pivotal year in which America fought for and won its independence.",
    "The Diary of a Young Girl (Definitive Edition)": "The complete and restored diary of Anne Frank during her years in hiding from the Nazis.",
    "The Origin of Species": "Darwin's groundbreaking 1859 work introducing the theory of evolution by natural selection.",
    "Cosmos": "Carl Sagan's lyrical exploration of the universe, from the Big Bang to the search for extraterrestrial intelligence.",
    "The Double Helix": "James Watson's personal account of the discovery of the structure of DNA and the race to unravel life's secret.",
    "Surely You're Joking, Mr. Feynman!": "Physicist Richard Feynman's hilarious and brilliant memoir of a life lived with insatiable curiosity.",
    "The Gene: An Intimate History": "A sweeping history of the gene and how our growing ability to manipulate DNA will change humanity.",
    "Being Mortal": "Atul Gawande examines how medicine can improve end-of-life care and what it means to die well.",
    "The Emperor of All Maladies": "A biography of cancer tracing its history from ancient times to modern treatments.",
    "The Body Keeps the Score": "Bessel van der Kolk reveals how trauma reshapes the body and brain, and explores innovative treatments.",
    "Influence": "Robert Cialdini identifies six key principles of persuasion that govern how we are influenced by others.",
    "Quiet: The Power of Introverts": "Susan Cain argues that introverts are undervalued in a world that celebrates extroversion.",
    "Flow": "Psychologist Mihaly Csikszentmihalyi explores the state of optimal experience and how to achieve it.",
    "The Interpretation of Dreams": "Freud's landmark 1899 work introducing the idea that dreams are the royal road to the unconscious mind.",
    "Deep Work": "Cal Newport argues that focused, distraction-free work is the key skill of the 21st century knowledge economy.",
    "Mindset": "Carol Dweck's research shows that a growth mindset believing abilities can be developed leads to greater achievement.",
    "The Subtle Art of Not Giving a F*ck": "Mark Manson's counterintuitive approach to living a good life by choosing what truly matters.",
    "Ikigai": "The Japanese concept of finding life's purpose through the intersection of passion, mission, vocation, and profession.",
    "Grit": "Angela Duckworth's research shows that passion and perseverance not talent predict outstanding achievement.",
    "Zero to One": "Peter Thiel's contrarian thinking on building startups that create genuinely new things rather than copying existing ones.",
    "The Lean Startup": "Eric Ries introduces a methodology for developing businesses and products that aims to shorten product development cycles.",
    "Good to Great": "Jim Collins' research reveals why some companies make the leap to greatness and others don't.",
    "The Innovator's Dilemma": "Why successful companies fail when confronted with disruptive innovation, and what to do about it.",
    "Thinking in Systems": "Donella Meadows introduces systems thinking as a way to understand and solve complex real-world problems.",
    "The Hard Thing About Hard Things": "Ben Horowitz shares hard-won insights on building and running a startup from someone who has done it.",
    "Shoe Dog": "Phil Knight's memoir about the creation of Nike from a $50 loan to a multi-billion dollar empire.",
    "Educated": "Tara Westover's memoir of growing up in a survivalist family in rural Idaho and educating herself into Cambridge.",
    "Becoming": "Michelle Obama's intimate and powerful memoir of her journey from Chicago's South Side to the White House.",
    "The Story of My Experiments with Truth": "Mahatma Gandhi's autobiography tracing his spiritual and political journey toward nonviolent resistance.",
    "Leonardo da Vinci": "Walter Isaacson's biography of history's greatest creative genius, based on Leonardo's notebooks.",
    "Einstein: His Life and Universe": "A comprehensive biography of Albert Einstein exploring his scientific breakthroughs and complex personal life.",
    "Alexander Hamilton": "Ron Chernow's definitive biography of the Founding Father who shaped modern America.",
    "The Autobiography of Malcolm X": "Malcolm X's powerful autobiography tracing his transformation from street criminal to Black nationalist leader.",
    "Meditations": "Personal writings of Roman Emperor Marcus Aurelius on Stoic philosophy, duty, and self-improvement.",
    "Thus Spoke Zarathustra": "Nietzsche's philosophical novel presenting his ideas on the Ubermensch, will to power, and eternal recurrence.",
    "Beyond Good and Evil": "Nietzsche challenges traditional moral values and calls for a revaluation of all values.",
    "The Republic": "Plato's foundational work on justice, the ideal state, and the nature of the philosopher-king.",
    "Nicomachean Ethics": "Aristotle's treatise on virtue, happiness, and the good life that has shaped Western moral philosophy.",
    "Being and Nothingness": "Sartre's major philosophical work laying out the foundations of existentialism and radical human freedom.",
    "The Stranger": "Meursault kills an Arab on an Algerian beach and faces trial not for the murder but for his emotional indifference.",
    "Siddhartha": "A young Brahmin leaves his privileged life to seek enlightenment, eventually finding it through lived experience.",
    "The Mythical Man-Month": "Fred Brooks' classic essays on software engineering project management and why adding manpower slows projects.",
    "Design Patterns": "The Gang of Four's landmark catalog of reusable object-oriented software design solutions.",
    "You Don't Know JS": "A deep dive into JavaScript's core mechanisms that most developers misunderstand or overlook.",
    "The Linux Command Line": "A comprehensive introduction to using the Linux command line for beginners and experienced users alike.",
    "Automate the Boring Stuff with Python": "Practical Python programming for total beginners, teaching automation of everyday computer tasks.",
    "The Phoenix Project": "A novel about IT, DevOps, and helping your business win, told through a company facing catastrophic project failure.",
    "Cracking the Coding Interview": "189 programming interview questions with solutions and strategies for landing a job at top tech companies.",
    "The Man Who Knew Infinity": "The biography of Srinivasa Ramanujan, the self-taught mathematical genius from India.",
    "Fermat's Last Theorem": "The story of the 350-year quest to prove Fermat's deceptively simple mathematical conjecture.",
    "How to Solve It": "George Polya's classic guide to mathematical problem-solving strategies applicable to any discipline.",
    "The Art of Problem Solving Vol. 1": "The definitive guide for students preparing for mathematics competitions at all levels.",
    "Into the Wild": "The true story of Chris McCandless who abandoned his possessions to live in the Alaskan wilderness.",
    "Into Thin Air": "Jon Krakauer's harrowing first-hand account of the 1996 Mount Everest disaster that killed eight climbers.",
    "The Call of the Wild": "A domesticated dog is thrust into the brutal life of the Yukon gold rush and rediscovers his wild nature.",
    "Treasure Island": "Young Jim Hawkins embarks on a dangerous sea voyage to find buried pirate treasure.",
    "Around the World in 80 Days": "English gentleman Phileas Fogg bets he can circumnavigate the globe in 80 days.",
    "Twenty Thousand Leagues Under the Sea": "Captain Nemo takes prisoners on an extraordinary voyage aboard his submarine the Nautilus.",
    "Death of a Salesman": "Arthur Miller's masterpiece about the tragic collapse of Willy Loman and the American Dream.",
    "A Raisin in the Sun": "A Black family in 1950s Chicago debates how to spend a life insurance check in Hansberry's groundbreaking play.",
    "The Glass Menagerie": "Tennessee Williams' memory play about a domineering mother, her restless son, and her fragile daughter.",
    "Hamlet": "Shakespeare's tragic masterpiece about a Danish prince torn between action and inaction after his father's murder.",
    "Macbeth": "Shakespeare's darkest tragedy follows a Scottish general whose ambition, spurred by witches, leads to his downfall.",
    "Romeo and Juliet": "The timeless tragedy of two young lovers from feuding families whose love ends in heartbreak.",
    "Othello": "Shakespeare's tragedy of jealousy and manipulation as Iago destroys the noble Moor Othello.",
    "The Bible (NIV)": "The New International Version of the sacred scriptures of Christianity, containing the Old and New Testaments.",
    "The Quran (English Translation)": "M.A.S. Abdel Haleem's acclaimed English translation of Islam's holy scripture.",
    "The Bhagavad Gita": "The ancient Hindu scripture presenting a conversation between Prince Arjuna and the god Krishna on duty and righteousness.",
    "The Tao Te Ching": "Laozi's ancient Chinese text of 81 verses on the nature of the Tao and how to live in harmony with it.",
    "Man's Search for Meaning": "Viktor Frankl's profound account of survival in Nazi death camps and his discovery of meaning as life's driving force.",
    "Rich Dad Poor Dad": "Robert Kiyosaki contrasts the financial philosophies of his educated but poor father and his friend's wealthy father.",
    "The 7 Habits of Highly Effective People": "Stephen Covey's timeless principles for personal and interpersonal effectiveness.",
    "How to Win Friends and Influence People": "Dale Carnegie's classic guide to building meaningful relationships and influencing others positively.",
    "The Art of War": "Sun Tzu's ancient treatise on military strategy has become essential reading for business and leadership.",
    "Steve Jobs": "Walter Isaacson's authorized biography reveals the genius, passion, and demons of Apple's visionary founder.",
    "Atomic Habits": "A practical guide to building good habits and breaking bad ones through small, incremental changes.",
    "The Alchemist": "A shepherd boy travels from Spain to Egypt in pursuit of his personal legend, learning profound life lessons along the way.",
    "The Diary of a Young Girl": "Anne Frank's moving account of hiding from the Nazis in a secret Amsterdam annex during World War II.",
    "The Hobbit": "Bilbo Baggins, a comfort-loving hobbit, embarks on an unexpected adventure with a group of dwarves to reclaim their mountain home.",
}

with app.app_context():
    added = 0
    skipped = 0
    for b in books:
        if not Book.query.filter_by(isbn=b['isbn']).first():
            book = Book(
                title=b['title'],
                author=b['author'],
                isbn=b['isbn'],
                category=b['category'],
                cover_image=b['cover'],
                total_copies=b['copies'],
                available_copies=b['copies'],
                rating=b.get('rating', 4.0),
                description=descriptions.get(b['title'], '')
            )
            db.session.add(book)
            added += 1
        else:
            skipped += 1
    db.session.commit()
    print(f'Done. Added: {added} books. Skipped (already exist): {skipped}')